### ISSUE TITLE
Enable integration tests (testsuite module) incrementally

### ISSUE THREAD

**Issue by fabiobrz** [Intersmash/intersmash#21]
The Intersmash integration tests in the `testsuite` module should be enabled incrementally until they work with default community bits and images/templates/charts, so that global-test.properties can be populated accordingly.

- [x] WildflyBootableJarTestCase - see #19 
- [x] WildflyJavaxBootableJarTestCase - see #19 
- [x] InfinispanOperatorProvisionerTest - see #25 
- [x] WildflyOperatorProvisionerTest - see #30 
- [x] HyperfoilOperatorTest - see #31
- [x] KafkaOperatorProvisionerTest - see #35 
- [x] MysqlImageTestCase - see #38 
- [x] PostgreSQLImageTestCase - see #38 
- [x] ActiveMQOperatorProvisionerTest - also tracked by #32, see #45
- [x] KeycloakOperatorProvisionerTest - also tracked by #37, see #57
- [x] WildflyImageTestCase (to be renamed to WildflyImageProvisionerTestCase) - see #42 
- [x] WildflyHelmChartProvisionerTest - see #46 
- [x] WildflyTargetServerTestCase - see #50 
- [x] WildflyMavenProjectTestCase - see #52 
- [x] OperatorSubscriptionTestCase see #53 

---
* Environment: running integration tests
* Steps to reproduce: `mvn clean install -DskipTests ; mvn clean test -pl testsuite/`

**Comment by fabiobrz** [comment]
Closing as resolved, via the linked PRs in the issue description.
