### ISSUE TITLE
JOSDK implementation for existing Operator based provisioners is not based on a unique approach

### ISSUE THREAD

**Issue by fabiobrz** [Intersmash/intersmash#67]
The Java Operator SDK, i.e. the Java object model for interacting with the Custom Resources, implementation is mostly relying on a manual coding approach, but we experimented already with the Fabric8 Kubernetes CLient Java Generator, and it has been integrated in Intersmash already, e.g.: for the Hyperfoil and ActiveMQ Artemis operator provisioners.

This way we'd remove a lot of boiler-plate code, hard to maintain and error prone.

This issue is for tracking the effort needed to align the implementation to the _contract-first_ approach and have a JOSDK model being generated at build time.  

- [x] WildFly Operator based provisioner :heavy_check_mark: - see #92 
- [x] Keycloak RealmImport (latest/WIP, 22.x) Operator based provisioner (done, just replace URLs with actual CRD resources) -:heavy_check_mark: - see #94 
- [x] Infinispan Operator based provisioner - :heavy_check_mark: see #96 
- [x] ActiveMQ Broker Operator based provisioner (done, just validate) :heavy_check_mark: - see #95 
- [x] Kafka Operator based provisioner (done, Java operator already via Strimzi)
- [x] Hyperfoil Operator based provisioner (done, just validate)
- [x] Freeze versions in docs - **WIP** - see #101 
- [x] Update docs related to operator provisioning to align with generated JOSDK - **WIP** - see #101 

---
* Environment: N/A, the tools/intersmash-tools-provisioners submodule from a project structure perspective
* Steps to reproduce: N/A
