### ISSUE TITLE
[iisue 80] - Add EAP 7 provisioning tooling

### ISSUE THREAD

**Issue by fabiobrz** [Intersmash/intersmash#80]
**Is your feature request related to a problem? Please describe.**
Follows up on [https://github.com/Intersmash/intersmash/pull/70](https://github.com/Intersmash/intersmash/pull/70#issuecomment-1651565391) - in the context of using Intersmash with productized bits and deliverables, see https://github.com/Intersmash/intersmash/issues/62

This is mainly needed to use Intersmash for testing the EAP 7 stream.

**Describe the solution you'd like**

- [x] EAP 7 Image provisioner: **Done**, see #98 
- [x] EAP 7 Template based provisioner: **Done**, see  #104 
- [x] EAP 7 s2i Build provisioner - **Done**, see #106

**Describe alternatives you've considered**
Rework internal tests that are currently using EAP image and template based provisioners in order to use different ones but that would require for more work and time.

**Additional context**
N/A
